apiVersion: v1
kind: Service
metadata:
  name: petclinic-service-preprod
  namespace: pre-prod
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http    # Add this line
  selector:
    app: petclinic
